#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2012 SjB <steve@sagacity.ca>. All Rights Reserved.

TestApp = 'HidCliTest'

srcs = ['hid_cli_test.cs']

uselib = ['SjB.Hid']

bld(
    features = 'cs cs_dev',
    source = srcs,
    install_path = bld.env.default_app_install_path,
    gen = '{0}.exe'.format(TestApp),
    type = 'exe',
    use = uselib
)
