#!/usr/bin/env python
# encoding: utf-8
# Steve Beaulac, 2013 (SjB)

bld.shlib(
	source = 'hid-cli.c',
	target = 'hid-cli',
	includes = ['../include'],
    install_path = bld.env.default_app_install_path,
	vnum = bld.env.Version)
