#!/usr/bin/env python
# enccoding: utf-8
# Steve Beaulac, 2013 (SjB)

APPNAME="hid-cli"

srcs = [
#   'dllmain.cpp',
#    'stdafx.cpp',
    'hid-cli.cpp']

bld.read_stlib('hid', paths=['/usr/i586-mingw32msvc/lib']);
bld.read_stlib('setupapi', paths=['/usr/i586-mingw32msvc/lib']);

DEFINES = [
    'STRICT=1',
    'WINVER=0x0400',
    '__GNUWIN32__',
    '__WIN95__',
    'HAVE_W32API_H',
    '_WXMSW_',
    '_WINDOWS_',
    'HIDCLI_EXPORTS']

bld.shlib(
    source = srcs,
    target = 'hid-cli',
    vnum = bld.env.Version,
    defines = DEFINES,
    dflags = ['-g'],
    includes = [
    '../include',
    '/usr/i586-mingw32msvc/include',
    '/usr/i586-mingw32msvc/include/ddk'],
    use = 'setupapi hid')
